tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "mas"

brew "git"
brew "ruby-build"
brew "rbenv"
brew "awscli"

mas "1Password 7", id: 1333542190
mas "CotEditor", id: 1024640650
mas "Slack", id: 803453959
mas "Magnet", id: 441258766

cask "karabiner-elements"
cask "discord"
cask "istat-menus"
cask "iterm2"
cask "visual-studio-code"
cask "zoomus"
cask "google-chrome"
cask "amorphousdiskmark"

grooup :private do
  brew "youtube-dl"
end
